#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

LOCKFILE=/app/.entrypoint.lock

if [[ ! -f ${LOCKFILE} ]]; then
  python /app/manage.py makemigrations
  python /app/manage.py migrate
  python /app/manage.py createsuperuser --noinput --skip-checks
  if [[ "${SAMPLE_PROJECTS}" =~ [Tt][Rr][Uu][Ee] ]]; then
    python /app/manage.py seed
  fi
  #PGPASSWORD=${POSTGRES_PASS} psql ${POSTGRES_DB} -U ${POSTGRES_USER} -p 5432 -h postgres -c "CREATE TABLE status (id serial primary key, done timestamp);"
  #PGPASSWORD=${POSTGRES_PASS} psql ${POSTGRES_DB} -U ${POSTGRES_USER} -p 5432 -h postgres -c "INSERT INTO status(done) values (now());"
  touch ${LOCKFILE}
fi


python /app/manage.py collectstatic --noinput

compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python /app/manage.py compress --force
fi

uvicorn config.asgi:application --host 0.0.0.0 --reload
/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
