# Generated by Django 3.2.13 on 2022-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevAppExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, verbose_name='Short Name')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Test Item Abstract')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Test Item',
                'verbose_name_plural': 'Test Items',
            },
        ),
    ]
