# Generated by Django 3.2.13 on 2022-07-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devappexample',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='dev/media'),
        ),
    ]
