# Generated by Django 3.2.13 on 2022-07-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_user', to='credits.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='User Detail'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Status'),
        ),
    ]
