# Generated by Django 3.2.13 on 2022-07-29 10:44

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import geodata_mart.users.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_user', to='credits.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/geodata/assets', location='/qgis'), upload_to=geodata_mart.users.models.User.getUserUploadPath, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='User Detail'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Status'),
        ),
    ]
