# Generated by Django 3.2.13 on 2022-07-27 20:03

import django.core.files.storage
from django.db import migrations
import geodata_mart.users.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220726_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/geodata/assets', location='/qgis'), upload_to=geodata_mart.users.models.User.getUserUploadPath, verbose_name='Avatar'),
        ),
    ]
