# Generated by Django 3.2.13 on 2022-07-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='29712c9b040144819b5230d2ec5fe075', max_length=32, verbose_name='Job ID'),
        ),
    ]
