# Generated by Django 3.2.13 on 2022-07-29 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_id', to='vendors.vendor', verbose_name='Data Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='processingscriptfile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='processingmodelfile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='pgservicefile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AddField(
            model_name='metatags',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_maps_metatags_related_+', to='maps.MetaTags'),
        ),
        migrations.AddField(
            model_name='layer',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='layer',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_maps_layer_siblings_+', to='maps.Layer'),
        ),
        migrations.AddField(
            model_name='layer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maps.MetaTags'),
        ),
        migrations.AddField(
            model_name='job',
            name='layers',
            field=models.ManyToManyField(blank=True, to='maps.Layer', verbose_name='Map Layers'),
        ),
        migrations.AddField(
            model_name='job',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maps.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='downloadabledataitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maps.MetaTags'),
        ),
        migrations.AddField(
            model_name='downloadabledataitem',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_files', to='vendors.vendor', verbose_name='Data Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='authdbfile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='resultfile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='projectdatafile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='projectcoveragefile',
            unique_together={('file_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('short_name', 'project_id')},
        ),
        migrations.AlterUniqueTogether(
            name='downloadabledataitem',
            unique_together={('file_name', 'version')},
        ),
    ]
