# Generated by Django 3.2.13 on 2022-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_layers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Maximum Layers'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Define whether this layer should be checked by default', verbose_name='Default'),
        ),
    ]
