# Generated by Django 3.2.13 on 2022-08-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_srs',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_srs', to='maps.SpatialReferenceSystem', verbose_name='SRS List'),
        ),
    ]
