# Generated by Django 3.2.13 on 2022-07-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='2673b82ee5d448fda69a32200f731f8e', max_length=32, verbose_name='Job ID'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='short_name',
            field=models.CharField(max_length=80, verbose_name='Layer Short Name'),
        ),
    ]
