# Generated by Django 3.2.13 on 2022-07-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20220725_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='authdbfile',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Master Key'),
        ),
    ]
