# Generated by Django 3.2.13 on 2022-08-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_project_allowed_srs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowed_srs',
            field=models.ManyToManyField(blank=True, related_name='allowed_srs', to='maps.SpatialReferenceSystem', verbose_name='SRS List'),
        ),
    ]
