# Generated by Django 3.2.13 on 2022-07-11 20:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20220711_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='file_object',
            field=models.FileField(blank=True, help_text='Resulting output file from processing jobs', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/geodata/assets', location='/qgis'), upload_to='./results', verbose_name='Results File'),
        ),
    ]
