# Generated by Django 3.2.13 on 2022-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_resultfile_file_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='lyr_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Layer Group'),
        ),
    ]
