# Generated by Django 3.2.13 on 2022-07-12 16:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_layer_lyr_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coverage',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, geography=True, null=True, srid=4326, verbose_name='Project Coverage Region'),
        ),
    ]
