# Generated by Django 3.2.13 on 2022-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, default='2687182135a94e4eb5bc7ef753cc5fbc', max_length=32, null=True, unique=True, verbose_name='Job ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='layers',
            field=models.ManyToManyField(blank=True, null=True, to='maps.Layer', verbose_name='Map Layers'),
        ),
        migrations.AlterField(
            model_name='job',
            name='parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Request Parameters'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Abandoned'), (2, 'Unfulfilled'), (3, 'Processed'), (4, 'Completed'), (5, 'Failed'), (6, 'Processing'), (7, 'Unknown'), (8, 'Stale'), (9, 'Other')], default=0, null=True),
        ),
    ]
