# Generated by Django 3.2.13 on 2022-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20220707_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, default='ff55dbbcfb4b4eb293ddd04799d9a4c6', max_length=32, null=True, unique=True, verbose_name='Job ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='layers',
            field=models.ManyToManyField(to='maps.Layer', verbose_name='Map Layers'),
        ),
    ]
