# Generated by Django 3.2.13 on 2022-07-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_alter_project_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Define whether this layer should be checked by default', verbose_name='Default'),
        ),
    ]
