# Generated by Django 3.2.13 on 2022-07-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_layer_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='buffer_default',
            field=models.FloatField(default=1, verbose_name='Default Buffer (km)'),
        ),
        migrations.AddField(
            model_name='project',
            name='buffer_max',
            field=models.FloatField(default=10.0, verbose_name='Buffer Max'),
        ),
        migrations.AddField(
            model_name='project',
            name='buffer_min',
            field=models.FloatField(default=0.0, verbose_name='Buffer Min'),
        ),
        migrations.AddField(
            model_name='project',
            name='buffer_step',
            field=models.FloatField(default=0.5, verbose_name='Buffer Increment'),
        ),
    ]
