# Generated by Django 3.2.13 on 2022-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20220707_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, default='efca479f308f49619273612c47c48701', max_length=32, null=True, unique=True, verbose_name='Job ID'),
        ),
    ]
