# Generated by Django 3.2.13 on 2022-07-17 00:35

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20220716_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCoverageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('version', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('file_object', models.FileField(blank=True, help_text='Spatial data file for definition of project coverage', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/geodata/assets', location='/qgis'), upload_to='./projects/coverages', verbose_name='Project Coverage File')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Loaded'), (2, 'Error')], default=0, null=True)),
                ('project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_file', to='maps.project')),
            ],
            options={
                'verbose_name': 'Project Coverage File',
                'verbose_name_plural': 'Project Coverage Files',
                'abstract': False,
                'unique_together': {('file_name', 'version')},
            },
        ),
    ]
