# Generated by Django 3.2.13 on 2022-07-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, default='2e1e0963f4aa4d9585b02ea5ae996e9a', max_length=32, null=True, unique=True, verbose_name='Job ID'),
        ),
    ]
