# Generated by Django 3.2.13 on 2022-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, default='a0fdaf23e6b149b88cfb3c1cd844df29', max_length=32, null=True, unique=True, verbose_name='Job ID'),
        ),
    ]
