#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"

until PGPASSWORD=${POSTGRES_PASS} psql -h "${POSTGRES_HOST}" -U ${POSTGRES_USER} -d ${POSTGRES_DB} -P "pager=off" -c '\l'; do
  >&2 echo "${POSTGRES_DB} is unavailable - sleeping"
  sleep 1
done
>&2 echo "${POSTGRES_DB} databases is up "


exec "$@"
