# Generated by Django 3.2.13 on 2022-07-29 10:44

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import geodata_mart.vendors.models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Vendor Name')),
                ('abstract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Abstract')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Vendor Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/geodata/assets', location='/qgis'), upload_to=geodata_mart.vendors.models.Vendor.getVendorUploadPath, verbose_name='Logo')),
                ('media', versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/geodata/assets', location='/qgis'), upload_to=geodata_mart.vendors.models.Vendor.getVendorUploadPath, verbose_name='Media')),
                ('admins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Administrators')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Employees')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
        migrations.CreateModel(
            name='VendorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maps.job')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.vendormessage')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maps.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='vendors.vendor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
