#!/bin/bash

set -o errexit
set -o nounset

LOCKFILE=/app/.entrypoint.lock
while [ ! -f ${LOCKFILE} ]
do
  sleep 2
done

celery \
    -A config.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
